# fly.toml (Versão Corrigida e Final)

app = "forms-perform"
primary_region = "gru"

[build]
  builder = "paketobuildpacks/builder:base"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256

# A seção abaixo é a correção principal.
# Ela diz ao Fly.io qual comando deve ser mantido em execução.
[processes]
  app = "gunicorn app:app --bind :8080 --workers 2"